version: '3.9'

services:
  # Mongodb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo_data:/data/db
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - 3306:3306

  # Node api service
  db_api:
    container_name: db_api
    image: nodeapp
    ports:
      - 3030:3030
    depends_on: 
      - mongo_db

  sentiment_analyzer:
    container_name: sentiment-analyzer
    image: sentiment-analyzer
    ports:
      - 5001:5001

  django:
    container_name: dealership
    image: dealership
    ports:
      - 8001:8001
    environment:
      - backend_url=http://db_api:3030
      - sentiment_analyzer_url=http://sentiment-analyzer:5001
    depends_on: 
      - mongo_db
      - sentiment_analyzer
      - db_api


volumes:
  mongo_data: {}
