apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api-deployment
  namespace: dealership
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
        - name: node-api
          image: nodeapp:1.2
          livenessProbe:
            httpGet:
              path: /health
              port: 3030
          ports:
            - containerPort: 3030