apiVersion: v1
kind: Service
metadata:
  name: node-api-service
  namespace: dealership
spec:
  selector:
    app: node-api
  ports:
    - protocol: TCP
      port: 3030
      targetPort: 3030
  type: LoadBalancer
