apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: dealership
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /Users/jiawen/Documents/dev/mongodata
